dist: trusty
sudo: required
language: generic
services:
- docker
env:
  global:
    - BINARY=travis-docker-rust-cross
    - BUILD_OS=linux
  matrix:
    - ARCH=armv7hf TARGET=armv7-unknown-linux-gnueabihf
    - ARCH=rpi TARGET=arm-unknown-linux-gnueabihf
    - ARCH=i386 TARGET=i686-unknown-linux-gnu
    - ARCH=amd64 TARGET=x86_64-unknown-linux-gnu
install: true
script: ci/script.sh
before_deploy:
  - mkdir -p $TRAVIS_TAG
  - sudo mv target/$TARGET/release/$BINARY $TRAVIS_TAG/$BINARY-$TRAVIS_TAG-$BUILD_OS-$ARCH
deploy:
  provider: s3
  access_key_id: AKIAJOM2KL3KOMF4ZGHA
  secret_access_key:
    secure: Y8uM817pacSZ916FD+r3FjYirCbruXBwRNAq/nd1UGd/CdU4kv9euV01aR0Eba5d+VBDKmT/7+3qWYK68+MCflvQXO3KvcBumBOarLBGcImyTBPErGe94H5ahpVKm+HpeYENW26XmwdwaWYup4oVeyB7qkSE3vDbh0mO37DdOxLXW9kb3OQyyWW2PKmd/ZMRk0bcZN730iFIL9Ez+Lbyu6rCFjLdk1qU/K2GZaQ6BkUttZFPa8oQjBxpZgmAJTlZ0133hpGUoowGI1HYMyq+VdE79L6DmEvjzRsVQJxtySynVjAmptVUpP5VLzIAnSzCi2ZTjIWqvTsuFRPFCu0lfWD10yNLQJ+pyVNfxEO0nX7L/3M704t19cbhHY95ZVgWuaMWbj3rFFpyPEYozyGsWVnY3zV9NCpUI7M4yxybg+HhvoXqoiOWLPsZZLBO+lEY4UMj7og6Gx23WybkbdwHCgJbTxNGLoNdnF7azDmDKt0FAk+McqcnTSu9FOxv3FOLah1/qi6/Oog+Di7HiGjXYLk5jwuvQGvhaKAYOMWkOMafrAqa+rtP/bwrCiGWQvpLJMVTAvoseACSjs/QYFepMv800h45qTpJM6anHw/BPs4TKCSEP3KLDhB99aLaoD4CTcijOO4SSsyK8KC6LzTvwjPyxDPjCPfDDATT82VF8eg=
  skip_cleanup: true
  overwrite: true
  bucket: travis-docker-rust-cross
  local-dir: "$TRAVIS_TAG"
  upload-dir: $BINARY/$TRAVIS_TAG
  acl: public_read
  on:
    branch: master
    tags: true
after_deploy: ci/release.sh "* [$BINARY-$TRAVIS_TAG-$BUILD_OS-$ARCH](https://travis-docker-rust-cross.s3.amazonaws.com/$BINARY/$TRAVIS_TAG/$BINARY-$TRAVIS_TAG-$BUILD_OS-$ARCH)"
notifications:
  email: false
