dist: trusty
sudo: required

services:
  - docker

env:
  matrix:
    - TARGET=x86_64-unknown-linux-gnu
    - TARGET=i686-unknown-linux-gnu
    - TARGET=arm-unknown-linux-gnueabihf
    - TARGET=armv7-unknown-linux-gnueabihf

before_install:
  - docker build -t "$TARGET" ci/docker/"$TARGET"

script:
  - docker --version
  - docker run -it --rm -v ${PWD}:/work "$TARGET" cargo build --target="$TARGET"
