dist: trusty
sudo: required

services:
  - docker

before_install:
  - docker build --cache-from travis-docker-rust-cross/arm-unknown-linux-gnueabihf -t travis-docker-rust-cross/arm-unknown-linux-gnueabihf ci/docker/arm-unknown-linux-gnueabihf

script:
  - docker --version
  - docker run -it --rm -v ${PWD}:/work travis-docker-rust-cross/arm-unknown-linux-gnueabihf cargo build --target=arm-unknown-linux-gnueabihf
